# syntax=docker/dockerfile:1.5
# vim:ft=dockerfile

# docker run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:rw --ipc=host --user $(id -u):$(id -g) mesycontrol:latest mesycontrol_gui

# Dockerfile for building mesycontrol_server and the full client package.

# Image creation:
#   docker build  -f ./Dockerfile.debian-stable -t mesycontrol:latest .

# Running the server:
#   docker run --rm mesycontrol:latest /dev/ttyUSB0

# Using the script runner:

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="Etc/UTC"
# Set to 1 for extra info to debug Qt plugin loading and find possible missing
# libraries.
#ENV QT_DEBUG_PLUGINS=1


RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates build-essential git cmake python3-venv \
    libboost-all-dev libprotobuf-dev protobuf-compiler \
    libglib2.0-0 libgl1 libqt5widgets5

COPY . /mesycontrol-source

# Use pip to install the python client package, its dependencies and
# pyinstaller.
RUN python3 -m venv /mesycontrol-venv
ENV PATH="/mesycontrol-venv/bin:$PATH"
RUN python3 -m pip install --upgrade pip
WORKDIR /mesycontrol-source/src/client
RUN --mount=type=cache,target=/root/.cache \
    pip3 install . pyinstaller

# Run cmake to build both the server and frozen client packages.
WORKDIR /mesycontrol-build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mesycontrol \
    -DMESYCONTROL_BUILD_CLIENT=ON /mesycontrol-source \
    && make -j && make install

# Try to start the server and import the mesycontrol python package.
ENV PATH="/mesycontrol/bin:$PATH"
RUN mesycontrol_server --help
RUN python3 -c 'import mesycontrol'
RUN python3 -c 'from mesycontrol.mesycontrol_script_runner import script_runner_main; script_runner_main()'

# TODO: Keep the server running in the background and test if clients can
# connect and do work. If testing scripts like the auto poller, how do I tell
# these to exit? Add a singleshot or timeout option or kill via the shell? How
# to get the exit code?

# Default entrypoint is the server binary.
ENTRYPOINT ["/mesycontrol/bin/mesycontrol_server"]
