######################################################################
# Automatically generated by qmake (2.01a) Thu May 23 15:05:38 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += child_object.h main_object.h parent_object.h
SOURCES += child_object.cc main.cc main_object.cc parent_object.cc
