######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 27 15:31:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qgroupbox_editable_title.h
SOURCES += main.cc qgroupbox_editable_title.cc
