######################################################################
# Automatically generated by qmake (2.01a) Wed May 29 13:37:15 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
